### ISSUE TITLE
error when running demo script with python 3.6

### ISSUE THREAD

**Issue by fcoppey** [zmzhang/CTE2#1]
<img width="567" alt="screenshot 2018-10-02 at 09 59 31" src="https://user-images.githubusercontent.com/42648441/46336045-df78e100-c629-11e8-9159-ca73fae7dd67.png">
I get this error when running the demo script. any explanation as of why? I would like to use your script but it has no comments ,it's very hard...

**Comment by muba1** [comment]
having the same issue with python 3

**Comment by zmzhang** [comment]
@fcoppey @muba1 
We have ported TEAM to Python 3.
Now It can run in Python 3.6 and 3.7 smoothly.
Please see [this commit](https://github.com/zmzhang/TEAM/commit/4616c4044beff5e2e1a2c1f464fffd0124fe41a7).
